# This is an experimental Dockerfile with multistage dev build, 
# which utilizes the whole repo clone; hence, the image as a whole might be 
# pretty heavy. Production Dockerfile will be made leaner when 
# subpackage wheels would be production-ready too. 
#   1) install poetry and plugins from source to produce requirements.txt
#   2) install system libs, utilize requirements.txt via pip

# Builder: clone, install deps, build wheels
FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04 AS builder

# system dependencies 
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    git \
    cmake \ 
    openssh-client \
    software-properties-common \ 
    libopenblas-dev liblapack-dev \
    libgl1 libglib2.0-0 \
    && rm -rf /var/lib/apt/lists*

# explicitly install python3.10 from deadsnakes/ppa
RUN add-apt-repository ppa:deadsnakes/ppa \
    && apt-get update \
    && apt-get install -y \
    python3.10-dev \
    python3.10-venv \
    python3.10-distutils \ 
    && curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10 -

RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1 \
    && update-alternatives --install /usr/bin/pip pip /usr/local/bin/pip3 1

RUN apt-get install -y python3-pybind11 pybind11-dev && apt-get remove -y python3-blinker

RUN mkdir -p /root/.ssh && \
    chmod 700 /root/.ssh && \
    ssh-keyscan github.com >> /root/.ssh/known_hosts

# prepare git and ssh on container
RUN --mount=type=ssh \
    git clone git@github.com:stankevich-mipt/MorphoBot.git /build

WORKDIR /build

# install poetry
RUN python3 -m pip install --no-cache-dir poetry

# install microservice with poetry in combination with nested packages
ENV POETRY_VIRTUALENVS_IN_PROJECT=true
RUN cd ./services/gender_translation && poetry add blinker && poetry install --no-interaction --no-ansi


# ---------------------
# Runtime: Minimal CUDA+Python runtime with Python 3.10
# ---------------------
FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04

RUN apt-get update && apt-get install -y --no-install-recommends curl \
    software-properties-common \ 
    && rm -rf /var/lib/apt/lists*

RUN add-apt-repository ppa:deadsnakes/ppa \
    && apt-get update \
    && apt-get install -y \
    python3.10 \ 
    python3.10-venv \
    python3.10-distutils \ 
    libopenblas-dev liblapack-dev \
    libgl1 libglib2.0-0 \
    && curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10 -

RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1

RUN python3 -m pip install --no-cache-dir poetry 

COPY --from=builder /build /app 

WORKDIR /app/services/gender_translation

RUN poetry install 

CMD ["poetry", "run", "python", "-m", "uvicorn", "gender_translation.main:app", "--host", "0.0.0.0", "--port", "8001"] 

