services:
  routing-api:
    build:
      context: ../../
      dockerfile: services/routing/Dockerfile.dev
      ssh: 
        default: ${SSH_AUTH_SOCK}
    container_name: routing-api
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      MLFLOW_S3_ENDPOINT_URL: ${MLFLOW_S3_ENDPOINT_URL}
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI} 
      MLFLOW_SERVER_DEFAULT_ARTIFACT_ROOT: ${MLFLOW_SERVER_DEFAULT_ARTIFACT_ROOT}
      MODEL_ALIAS: ${MODEL_ALIAS} 
      LOG_LEVEL: INFO
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "8000:8000"
    networks:
      - mlflow-network
    restart: unless-stopped
    

networks:
  mlflow-network:
    external: true