FROM nvidia/cuda:12.6.3-cudnn-devel-ubuntu22.04

# avoid timezone props
ENV DEBIAN_FRONTEND=noninteractive

# install python3.12 from ppa repository
RUN apt-get update && apt-get install -y \
    python3.10 \
    python3.10-dev \
    python3-pip \
    python3.10-venv \
    git \
    wget \
    curl \
    ffmpeg \
    libsm6 \ 
    libxext6 \
    libgl1-mesa-glx \
    libglib2.0-0 \
    build-essential \
    cmake \
    libboost-all-dev \
    && rm -rf /var/lib/apt/lists/*

# Set Python 3.10 as default
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.10 1
RUN update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1

# install poetry
RUN curl -sSL https://install.python-poetry.org | python -
ENV PATH="/root/.local/bin:$PATH"

# configure poetry
RUN poetry config virtualenvs.create false
RUN poetry config virtualenvs.in-project true

WORKDIR /workspace

# copy poetry files and install dependencies to cache them in the separate layer
COPY pyproject.toml poetry.lock* ./
# RUN poetry install --with dev --no-interaction --no-ansi 

# copy other git files nessesary for container development
COPY src/ ./src/
COPY configs/ ./configs/
COPY scripts/ ./scripts/
COPY notebooks/ ./notebooks/

EXPOSE 8888

CMD ["bash", "-lc", "sleep 432000"]